export const numOfEmployees = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "201-500",
  "500+",
];

export const jobType = ["Remote", "Hybrid", "In-office"];

export const techStack = [
  "Python",
  "Java",
  "C++",
  "GoLang",
  "Kotlin",
  "Ruby/Rails",
  "Django",
  "C#",
  "Flask",
  "GraphQL",
  "TypeScript",
  "AWS",
  "JavaScript",
  "Rust",
  "NodeJS",
  "React",
];

export const roles = {
  engineering: [
    "Backend",
    "Frontend",
    "FullStack",
    "IOS",
    "Flutter",
    "React Native",
    "Android",
    "Tech Lead",
    "Dev-Ops",
    "Data Engineer",
    "Data Science",
    "Computer-Vision",
    "Nlp",
    "Deep-Learning",
    "Test / Qa",
    "Web3",
    "SRE",
    "Data-Infrastructure",
  ],
  design: [
    "Designer",
    "Design Manager",
    "Graphic Designer",
    "Product Designer",
  ],
  product: ["Product Manager"],
  operations: ["Operations Manager", "Founder's Office / Chief of Staff"],
  sales: [
    "Sales Development Representative",
    "Account Executive",
    "Account Manager",
  ],
  marketing: [
    "Digital Marketing Manager",
    "Growth Hacker",
    "Marketing",
    "Product Marketing Manager",
  ],
  "other engineering": ["Hardware", "Mechanical", "Systems"],
  "business analyst": ["Business Analyst"],
  "data analyst": ["Data Analyst"],
  "project manager": ["Project Manager"],
  management: ["Management"],
  legal: ["Legal"],
  hr: ["Hr"],
  finance: ["Finance"],
};
